# Generated by Django 4.2.5 on 2023-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecaps',
            fields=[
                ('s_no', models.IntegerField(db_column='S_NO', primary_key=True, serialize=False)),
                ('s_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='S_Name', max_length=20, null=True)),
                ('course_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Course_name', max_length=20, null=True)),
                ('contact_no', models.DecimalField(blank=True, db_column='Contact_No', decimal_places=0, max_digits=12, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Mecaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=20, null=True)),
                ('branch', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Branch', max_length=20, null=True)),
                ('marks', models.IntegerField(blank=True, db_column='Marks', null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CITY', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Practice',
                'managed': False,
            },
        ),
    ]
